import breakfast from './images/breakfast.webp'
import lunch from './images/qelyanalti.webp'
import salad from './images/salad.webp'
import soup from './images/soup.webp'
import fish from './images/fish.webp'
import chicken from './images/chicken.webp'
import beef from './images/beef.webp'
import barbecue from './images/barbecue.webp'
import dough from './images/dough.webp'
import qarnir from './images/qarnir.webp'
import dessert from './images/dessert.webp'
import hotDrink from './images/hot-drink.webp'
import cola from './images/cola.webp'
import drinks from './images/drinks.webp'

export const categories = [
    {
        id: 1,
        title: "SƏHƏR YEMƏYİ",
        img: breakfast
    },
    {
        id: 2,
        title: "QƏLYANALTILAR",
        subTypes: [ "SOYUQ QƏLYANALTILAR", "İSTİ QƏLYANALTILAR" ],
        img: lunch
    },
    {
        id: 3,
        title: "SALATLAR",
        img: salad
    },
    {
        id: 4,
        title: "ŞORBALAR",
        img: soup
    },
    {
        id: 5,
        title: "BALIQ YEMƏKLƏRİ",
        img: fish
    },
    {
        id: 6,
        title: "TOYUQ YEMƏKLƏRİ",
        img: chicken
    },
    {
        id: 7,
        title: "ƏT YEMƏKLƏRİ",
        img: beef
    },
    {
        id: 8,
        title: "MANQAL",
        img: barbecue
    },
    {
        id: 9,
        title: "XƏMİR YEMƏKLƏRİ",
        img: dough
    },
    {
        id: 10,
        title: "QARNİRLƏR",
        img: qarnir
    },
    {
        id: 11,
        title: "DESERTLƏR",
        img: dessert
    },
    {
        id: 12,
        title: "İSTİ İÇKİLƏR",
        subTypes: [ "ÇAY", "QƏHVƏ" ],
        img: hotDrink
    },
    {
        id: 13,
        title: "ALKOQOLSUZ İÇKİLƏR",
        subTypes: [ "TƏBİİ ŞİRƏLƏR", "LİMONAD", "SƏRİN İÇKİLƏR" ],
        img: cola
    },
    {
        id: 14,
        title: "ALKOQOLLU İÇKİLƏR",
        subTypes: ["ŞAMPAN", "ŞƏRAB", "VİSKİ", "ARAQ", "PİVƏ", "KOKTEYLLƏR" ],
        img: drinks
    },
];


export const dishes = [
    {
        id: 1,
        title: "Fəsəli",
        type: "SƏHƏR YEMƏYİ",
        price: 8,
    },
    {
        id: 2,
        title: "Kükü",
        type: "SƏHƏR YEMƏYİ",
        price: 8,
    },
    {
        id: 3,
        title: "Pankeyk",
        type: "SƏHƏR YEMƏYİ",
        price: 6,
    },
    {
        id: 4,
        title: "Pendirli omlet",
        type: "SƏHƏR YEMƏYİ",
        price: 5,
    },
    {
        id: 5,
        title: "Pomidor çığırtması",
        type: "SƏHƏR YEMƏYİ",
        price: 7,
    },
    {
        id: 6,
        title: "Qayğanaq",
        type: "SƏHƏR YEMƏYİ",
        price: 3,
    },
    {
        id: 7,
        title: "Qlazok",
        type: "SƏHƏR YEMƏYİ",
        price: 3,
    },
    {
        id: 8,
        title: "Quymaq",
        type: "SƏHƏR YEMƏYİ",
        price: 10,
    },
    {
        id: 9,
        title: "Sade blinçik (3 əd)",
        type: "SƏHƏR YEMƏYİ",
        price: 5,
    },
    {
        id: 10,
        title: "Omlet",
        type: "SƏHƏR YEMƏYİ",
        price: 4,
    },
    {
        id: 11,
        title: "Kruassan",
        type: "SƏHƏR YEMƏYİ",
        price: 5,
    },
    {
        id: 12,
        title: "Təzə tərəvəz və göyərti",
        type: "QƏLYANALTILAR",
        subType: "SOYUQ QƏLYANALTILAR",
        price: 17,
    },
    {
        id: 13,
        title: "Turşu çeşidləri",
        type: "QƏLYANALTILAR",
        subType: "SOYUQ QƏLYANALTILAR",
        price: 22,
    },
    {
        id: 14,
        title: "Pendir assorti",
        type: "QƏLYANALTILAR",
        subType: "SOYUQ QƏLYANALTILAR",
        price: 33,
    },
    {
        id: 15,
        title: "Ət assorti",
        type: "QƏLYANALTILAR",
        subType: "SOYUQ QƏLYANALTILAR",
        price: 33,
    },
    {
        id: 16,
        title: "Julyen (2 nəfərlik)",
        type: "QƏLYANALTILAR",
        subType: "İSTİ QƏLYANALTILAR",
        price: 22,
    },
    {
        id: 17,
        title: "Blinçik kəsmiklə",
        type: "QƏLYANALTILAR",
        subType: "İSTİ QƏLYANALTILAR",
        price: 1,
    },
    {
        id: 18,
        title: "Blinçik ət ilə",
        type: "QƏLYANALTILAR",
        subType: "İSTİ QƏLYANALTILAR",
        price: 2,
    },
    {
        id: 19,
        title: "Qutab göyərti ilə",
        type: "QƏLYANALTILAR",
        subType: "İSTİ QƏLYANALTILAR",
        price: 1,
    },
    {
        id: 20,
        title: "Qutab ət ilə",
        type: "QƏLYANALTILAR",
        subType: "İSTİ QƏLYANALTILAR",
        price: 2,
    },
    {
        id: 21,
        title: "Çoban salatı",
        type: "SALATLAR",
        price: 8,
    },
    {
        id: 22,
        title: "Paytaxt salatı",
        type: "SALATLAR",
        price: 9,
    },
    {
        id: 23,
        title: "Pomidor salatı",
        type: "SALATLAR",
        price: 12,
    },
    {
        id: 24,
        title: "Sezar salatı",
        type: "SALATLAR",
        price: 19,
    },
    {
        id: 25,
        title: "Ət salatı",
        type: "SALATLAR",
        price: 22,
    },
    {
        id: 26,
        title: "Avokado salatı (2 nəfərlik)",
        type: "SALATLAR",
        price: 21,
    },
    {
        id: 27,
        title: "Rukkola salatı",
        type: "SALATLAR",
        price: 21,
    },
    {
        id: 28,
        title: "Mimoza salatı",
        type: "SALATLAR",
        price: 8,
    },
    {
        id: 29,
        title: "Manqal salatı",
        type: "SALATLAR",
        price: 12,
    },
    {
        id: 30,
        title: "Badımcan salatı (2 nəfərlik)",
        type: "SALATLAR",
        price: 18,
    },
    {
        id: 31,
        title: "Borş",
        type: "ŞORBALAR",
        price: 11,
    },
    {
        id: 32,
        title: "Balqabaq şorbası",
        type: "ŞORBALAR",
        price: 7,
    }, {
        id: 33,
        title: "Düşbərə",
        type: "ŞORBALAR",
        price: 7,
    },
    {
        id: 34,
        title: "Mərci şorbası",
        type: "ŞORBALAR",
        price: 7,
    },
    {
        id: 35,
        title: "Tərəvəz şorbası",
        type: "ŞORBALAR",
        price: 7,
    },
    {
        id: 36,
        title: "Qızıl balıq",
        type: "BALIQ YEMƏKLƏRİ",
        price: 33,
    },
    {
        id: 37,
        title: "Ballı krevetkalar düyü ilə",
        type: "BALIQ YEMƏKLƏRİ",
        price: 39,
    },
    {
        id: 38,
        title: "Forel",
        type: "BALIQ YEMƏKLƏRİ",
        price: 28,
    },
    {
        id: 39,
        title: "Berj",
        type: "BALIQ YEMƏKLƏRİ",
        price: 33,
    },
    {
        id: 40,
        title: "Nərə balığı",
        type: "BALIQ YEMƏKLƏRİ",
        price: 50,
    },
    {
        id: 41,
        title: "Çölmə kabab",
        type: "TOYUQ YEMƏKLƏRİ",
        price: 33,
    },
    {
        id: 42,
        title: "Kefli beçə",
        type: "TOYUQ YEMƏKLƏRİ",
        price: 31,
    },
    {
        id: 43,
        title: "Toyuq langeti",
        type: "TOYUQ YEMƏKLƏRİ",
        price: 17,
    },
    {
        id: 44,
        title: "Monastırsayağı toyuq",
        type: "TOYUQ YEMƏKLƏRİ",
        price: 22,
    },
    {
        id: 45,
        title: "Naqqetslər fri kartof ilə",
        type: "TOYUQ YEMƏKLƏRİ",
        price: 10,
    },
    {
        id: 46,
        title: "Setkada toyuq (2 nəfərlik)",
        type: "TOYUQ YEMƏKLƏRİ",
        price: 22,
    },
    {
        id: 47,
        title: "Toyuq çığırtması (2 nəfərlik)",
        type: "TOYUQ YEMƏKLƏRİ",
        price: 33,
    },
    {
        id: 48,
        title: "Cherry meat",
        type: "ƏT YEMƏKLƏRİ",
        price: 21,
    },
    {
        id: 49,
        title: "Daş altı",
        type: "ƏT YEMƏKLƏRİ",
        price: 21,
    },
    {
        id: 50,
        title: "Ət kətəsi",
        type: "ƏT YEMƏKLƏRİ",
        price: 20,
    },
    {
        id: 51,
        title: "Fransızsayağı ət",
        type: "ƏT YEMƏKLƏRİ",
        price: 21,
    },
    {
        id: 52,
        title: "Göbələkli rulet",
        type: "ƏT YEMƏKLƏRİ",
        price: 22,
    },
    {
        id: 53,
        title: "Quzu karesi kartof ilə",
        type: "ƏT YEMƏKLƏRİ",
        price: 22,
    },
    {
        id: 54,
        title: "Kiyevski kotlet",
        type: "ƏT YEMƏKLƏRİ",
        price: 20,
    },
    {
        id: 55,
        title: "Lanqet",
        type: "ƏT YEMƏKLƏRİ",
        price: 19,
    },
    {
        id: 56,
        title: "Medalyonlar can ətindən",
        type: "ƏT YEMƏKLƏRİ",
        price: 28,
    },
    {
        id: 57,
        title: "Yarpaq dolması",
        type: "ƏT YEMƏKLƏRİ",
        price: 13,
    },
    {
        id: 58,
        title: "Tikə (2 ədəd)",
        type: "MANQAL",
        price: 9,
    },
    {
        id: 59,
        title: "Antrikot",
        type: "MANQAL",
        price: 10,
    },
    {
        id: 60,
        title: "Lülə",
        type: "MANQAL",
        price: 9,
    },
    {
        id: 61,
        title: "Vişnəli döymə lülə",
        type: "MANQAL",
        price: 12,
    },
    {
        id: 62,
        title: "Badımcan lülə",
        type: "MANQAL",
        price: 12,
    },
    {
        id: 63,
        title: "Dana bastırma (2 ədəd)",
        type: "MANQAL",
        price: 12,
    },
    {
        id: 64,
        title: "Toyuq kababı",
        type: "MANQAL",
        price: 7,
    },
    {
        id: 65,
        title: "Set püstəli lülə",
        type: "MANQAL",
        price: 26,
    },
    {
        id: 66,
        title: "UFO kabab (2 nəfərlik)",
        type: "MANQAL",
        price: 35,
    },
    {
        id: 67,
        title: "Kartof quyruq",
        type: "MANQAL",
        price: 6,
    },
    {
        id: 68,
        title: "Tərəvəz kababı",
        type: "MANQAL",
        price: 6,
    },
    {
        id: 69,
        title: "Gürzə (7 ədəd)",
        type: "XƏMİR YEMƏKLƏRİ",
        price: 9,
    },
    {
        id: 70,
        title: "Xəngəl toyuq ilə",
        type: "XƏMİR YEMƏKLƏRİ",
        price: 22,
    },
    {
        id: 71,
        title: "Xəngəl ət ilə (+turşu və kompot)",
        type: "XƏMİR YEMƏKLƏRİ",
        price: 17,
    },
    {
        id: 72,
        title: "Gürcü xəngəli (1 ədəd)",
        type: "XƏMİR YEMƏKLƏRİ",
        price: 2.10,
    },
    {
        id: 73,
        title: "Düyü",
        type: "QARNİRLƏR",
        price: 5,
    },
    {
        id: 74,
        title: "Kartof ev sayağı",
        type: "QARNİRLƏR",
        price: 5,
    },
    {
        id: 75,
        title: "Kartof fri",
        type: "QARNİRLƏR",
        price: 5,
    },
    {
        id: 76,
        title: "Sote",
        type: "QARNİRLƏR",
        price: 5,
    },
    {
        id: 77,
        title: "Ballı tort",
        type: "DESERTLƏR",
        price: 10,
    },
    {
        id: 78,
        title: "San Sebastian",
        type: "DESERTLƏR",
        price: 10,
    },
    {
        id: 79,
        title: "Mirvari tort",
        type: "DESERTLƏR",
        price: 10,
    },
    {
        id: 80,
        title: "Napoleon",
        type: "DESERTLƏR",
        price: 10,
    },
    {
        id: 81,
        title: "Marakuya",
        type: "DESERTLƏR",
        price: 13,
    },
    {
        id: 82,
        title: "Red velvet",
        type: "DESERTLƏR",
        price: 13,
    },
    {
        id: 83,
        title: "Sladkıy noyabr",
        type: "DESERTLƏR",
        price: 13,
    },
    {
        id: 84,
        title: "Meyvə assortisi",
        type: "DESERTLƏR",
        price: 20,
    },
    {
        id: 85,
        title: "Dondurma",
        type: "DESERTLƏR",
        price: 6,
    },
    {
        id: 86,
        title: "Mürəbbə",
        type: "DESERTLƏR",
        price: 8,
    },
    {
        id: 87,
        title: "Qara çay",
        type: "İSTİ İÇKİLƏR",
        subType: "ÇAY",
        price: 10,
    },
    {
        id: 88,
        title: "Yaşıl çay",
        type: "İSTİ İÇKİLƏR",
        subType: "ÇAY",
        price: 10,
    },
    {
        id: 89,
        title: "Jasmin çay",
        type: "İSTİ İÇKİLƏR",
        subType: "ÇAY",
        price: 10,
    },
    {
        id: 90,
        title: "Espresso",
        type: "İSTİ İÇKİLƏR",
        subType: "QƏHVƏ",
        price: 4,
    },
    {
        id: 91,
        title: "Espresso double",
        type: "İSTİ İÇKİLƏR",
        subType: "QƏHVƏ",
        price: 6,
    },
    {
        id: 92,
        title: "Americano",
        type: "İSTİ İÇKİLƏR",
        subType: "QƏHVƏ",
        price: 5,
    },
    {
        id: 93,
        title: "Cappucino",
        type: "İSTİ İÇKİLƏR",
        subType: "QƏHVƏ",
        price: 8,
    },
    {
        id: 94,
        title: "Latte",
        type: "İSTİ İÇKİLƏR",
        subType: "QƏHVƏ",
        price: 8,
    },
    {
        id: 95,
        title: "Machiato",
        type: "İSTİ İÇKİLƏR",
        subType: "QƏHVƏ",
        price: 7,
    },
    {
        id: 96,
        title: "Coffee Glisse",
        type: "İSTİ İÇKİLƏR",
        subType: "QƏHVƏ",
        price: 10,
    },
    {
        id: 97,
        title: "Turkish coffee",
        type: "İSTİ İÇKİLƏR",
        subType: "QƏHVƏ",
        price: 8,
    },
    {
        id: 98,
        title: "Alma (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "TƏBİİ ŞİRƏLƏR",
        price: 8,
    },
    {
        id: 99,
        title: "Qreypfrut (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "TƏBİİ ŞİRƏLƏR",
        price: 10,
    },
    {
        id: 100,
        title: "Miks (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "TƏBİİ ŞİRƏLƏR",
        price: 12,
    },
    {
        id: 101,
        title: "Portağal (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "TƏBİİ ŞİRƏLƏR",
        price: 8,
    },
    {
        id: 102,
        title: "Ev üsulu limonad (1 lt)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "LİMONAD",
        price: 15,
    },
    {
        id: 103,
        title: "Limonad (1 bokal)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "LİMONAD",
        price: 6,
    },
    {
        id: 104,
        title: "Sirab qazlı (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 3,
    },
    {
        id: 105,
        title: "Sirab qazlı (0,75)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 6,
    },
    {
        id: 106,
        title: "Sirab qazsız (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 3,
    },
    {
        id: 107,
        title: "Sirab qazsız (0,75)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 6,
    },
    {
        id: 108,
        title: "Coca cola (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 4,
    },
    {
        id: 109,
        title: "Fanta (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 4,
    },
    {
        id: 110,
        title: "Sprite (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 4,
    },
    {
        id: 111,
        title: "Tonik (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 6,
    },
    {
        id: 112,
        title: "Red bull (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 8,
    },
    {
        id: 113,
        title: "Kompot (0,33)",
        type: "ALKOQOLSUZ İÇKİLƏR",
        subType: "SƏRİN İÇKİLƏR",
        price: 7,
    },
    {
        id: 114,
        title: "Prosecco (750 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "ŞAMPAN",
        price: 50,
    },
    {
        id: 115,
        title: "Prosecco Bokal",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "ŞAMPAN",
        price: 9,
    },
    {
        id: 116,
        title: "Meysəri (750 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "ŞƏRAB",
        price: 50,
    },
    {
        id: 117,
        title: "Meysəri Bokal",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "ŞƏRAB",
        price: 12,
    },
    {
        id: 118,
        title: "Chivas Regal 12 (50 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "VİSKİ",
        price: 12,
    },
    {
        id: 119,
        title: "Chivas Regal 18 (50 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "VİSKİ",
        price: 18,
    },
    {
        id: 120,
        title: "Absolut (50 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "ARAQ",
        price: 5,
    },
    {
        id: 121,
        title: "Finlandia (50 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "ARAQ",
        price: 6,
    },
    {
        id: 122,
        title: "Corona (330 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "PİVƏ",
        price: 8,
    },
    {
        id: 123,
        title: "Erdinger (500 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "PİVƏ",
        price: 10,
    },
    {
        id: 124,
        title: "Cosmopolitan",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "KOKTEYLLƏR",
        price: 12,
    },
    {
        id: 125,
        title: "Cuba Libre",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "KOKTEYLLƏR",
        price: 12,
    },
    {
        id: 126,
        title: "Gin&Tonik",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "KOKTEYLLƏR",
        price: 12,
    },
    {
        id: 127,
        title: "Mojito",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "KOKTEYLLƏR",
        price: 12,
    },
    {
        id: 128,
        title: "Negroni",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "KOKTEYLLƏR",
        price: 15,
    },
    {
        id: 129,
        title: "Tequila sunrise (50 ml)",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "KOKTEYLLƏR",
        price: 10,
    },
    {
        id: 130,
        title: "Margarita",
        type: "ALKOQOLLU İÇKİLƏR",
        subType: "KOKTEYLLƏR",
        price: 9,
    },
];
